### ISSUE TITLE
This plugin has a dependency on EC2 code

### ISSUE THREAD

**Issue by grahamc** [input-output-hk/nixops-packet#2]
```
Traceback (most recent call last):
  File "/nix/store/jnwss07vj3vpcknk2fl05qyi5s0n2spd-nixops-1.8pre2872_0cd267e/bin/.nixops-wrapped", line 251, in <module>
    args.op(args)
  File "/nix/store/jnwss07vj3vpcknk2fl05qyi5s0n2spd-nixops-1.8pre2872_0cd267e/lib/python2.7/site-packages/nixops/script_defs.py", line 427, in op_deploy
    max_concurrent_activate=args.max_concurrent_activate)
  File "/nix/store/jnwss07vj3vpcknk2fl05qyi5s0n2spd-nixops-1.8pre2872_0cd267e/lib/python2.7/site-packages/nixops/deployment.py", line 1062, in deploy
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/jnwss07vj3vpcknk2fl05qyi5s0n2spd-nixops-1.8pre2872_0cd267e/lib/python2.7/site-packages/nixops/deployment.py", line 1051, in run_with_notify
    f()
  File "/nix/store/jnwss07vj3vpcknk2fl05qyi5s0n2spd-nixops-1.8pre2872_0cd267e/lib/python2.7/site-packages/nixops/deployment.py", line 1062, in <lambda>
    self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
  File "/nix/store/jnwss07vj3vpcknk2fl05qyi5s0n2spd-nixops-1.8pre2872_0cd267e/lib/python2.7/site-packages/nixops/deployment.py", line 999, in _deploy
    nixops.parallel.run_tasks(nr_workers=-1, tasks=self.active_resources.itervalues(), worker_fun=worker)
  File "/nix/store/jnwss07vj3vpcknk2fl05qyi5s0n2spd-nixops-1.8pre2872_0cd267e/lib/python2.7/site-packages/nixops/parallel.py", line 44, in thread_fun
    result_queue.put((worker_fun(t), None, t.name))
  File "/nix/store/jnwss07vj3vpcknk2fl05qyi5s0n2spd-nixops-1.8pre2872_0cd267e/lib/python2.7/site-packages/nixops/deployment.py", line 972, in worker
    r.create(self.definitions[r.name], check=check, allow_reboot=allow_reboot, allow_recreate=allow_recreate)
  File "/nix/store/cd0r9zjr1k956dibk9hxkxnw9lr5gdn2-python2.7-nixops-packet-1.6.1pre2872_0cd267e/lib/python2.7/site-packages/nixopspacket/resources/keypair.py", line 70, in create
    self.access_key_id = defn.access_key_id or nixops.ec2_utils.get_access_key_id()
AttributeError: 'module' object has no attribute 'ec2_utils'
```

**Comment by johnalotoski** [comment]
Closed by PR https://github.com/input-output-hk/nixops-packet/pull/3
