### ISSUE TITLE
Destroying a cluster throws a key dep error for a machine that no longer exists

### ISSUE THREAD

**Issue by johnalotoski** [input-output-hk/nixops-packet#22]
Destroying a cluster with [a] key(s) and [a] machine(s) with the following command throws the following exception.
The workaround until resolved it just to re-issue the command.
```
$ nixops2 destroy -d packetDemo --debug
JSON output of nix-instantiate:
{"description":"packetDemo"}
warning: are you sure you want to destroy Packet.Net machine ‘machineDemo’? (y/N) y
machineDemo> destroying instance $DEVICE_ID
GET https://api.packet.net/devices/$DEVICE_ID {} {'X-Auth-Token': 'TOKEN', 'X-Consumer-Token': None, 'Content-Type': 'application/json'}
Starting new HTTPS connection (1): api.packet.net:443
https://api.packet.net:443 "GET /devices/$DEVICE_ID HTTP/1.1" 200 None
DELETE https://api.packet.net/devices/$DEVICE_ID {} {'X-Auth-Token': 'TOKEN', 'X-Consumer-Token': None, 'Content-Type': 'application/json'}
Starting new HTTPS connection (1): api.packet.net:443
https://api.packet.net:443 "DELETE /devices/$DEVICE_ID HTTP/1.1" 204 0
Traceback (most recent call last):
  File "/nix/store/wqrh0sqslkkjp860z5pl79wzrzpwymy9-python3.8-nixops-1.8.0/bin/.nixops-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/ih7p68vxgxasw47wcayq6cfy321j77mq-python3-3.8.3-env/lib/python3.8/site-packages/nixops/__main__.py", line 710, in main
    args.op(args)
  File "/nix/store/ih7p68vxgxasw47wcayq6cfy321j77mq-python3-3.8.3-env/lib/python3.8/site-packages/nixops/script_defs.py", line 661, in op_destroy
    depl.destroy_resources(
  File "/nix/store/ih7p68vxgxasw47wcayq6cfy321j77mq-python3-3.8.3-env/lib/python3.8/site-packages/nixops/deployment.py", line 1589, in destroy_resources
    self.run_with_notify(
  File "/nix/store/ih7p68vxgxasw47wcayq6cfy321j77mq-python3-3.8.3-env/lib/python3.8/site-packages/nixops/deployment.py", line 1447, in run_with_notify
    f()
  File "/nix/store/ih7p68vxgxasw47wcayq6cfy321j77mq-python3-3.8.3-env/lib/python3.8/site-packages/nixops/deployment.py", line 1590, in <lambda>
    "destroy", lambda: self._destroy_resources(include, exclude, wipe)
  File "/nix/store/ih7p68vxgxasw47wcayq6cfy321j77mq-python3-3.8.3-env/lib/python3.8/site-packages/nixops/deployment.py", line 1579, in _destroy_resources
    nixops.parallel.run_tasks(
  File "/nix/store/ih7p68vxgxasw47wcayq6cfy321j77mq-python3-3.8.3-env/lib/python3.8/site-packages/nixops/parallel.py", line 106, in run_tasks
    raise list(exceptions.values())[0]
  File "/nix/store/ih7p68vxgxasw47wcayq6cfy321j77mq-python3-3.8.3-env/lib/python3.8/site-packages/nixops/parallel.py", line 70, in thread_fun
    work_result = (worker_fun(t), None, t.name)
  File "/nix/store/ih7p68vxgxasw47wcayq6cfy321j77mq-python3-3.8.3-env/lib/python3.8/site-packages/nixops/deployment.py", line 1570, in worker
    if m.destroy(wipe=wipe):
  File "/nix/store/ih7p68vxgxasw47wcayq6cfy321j77mq-python3-3.8.3-env/lib/python3.8/site-packages/nixops_packet/resources/keypair.py", line 141, in destroy
    raise Exception(
Exception: keypair ‘$KEY’ is still in use by ‘machineDemo’ ($DEVICE_ID)

$ nixops2 destroy -d packetDemo --debug
JSON output of nix-instantiate:
{"description":"packetDemo"}
warning: are you sure you want to destroy keypair ‘$KEY’? (y/N) y
keyDemo> deleting Packet.net key pair ‘$KEY’...
GET https://api.packet.net/ssh-keys/$KEY_ID {} {'X-Auth-Token': 'TOKEN', 'X-Consumer-Token': None, 'Content-Type': 'application/json'}
Starting new HTTPS connection (1): api.packet.net:443
https://api.packet.net:443 "GET /ssh-keys/$KEY_ID HTTP/1.1" 200 None
DELETE https://api.packet.net/ssh-keys/$KEY_ID {} {'X-Auth-Token': 'TOKEN', 'X-Consumer-Token': None, 'Content-Type': 'application/json'}
Starting new HTTPS connection (1): api.packet.net:443
https://api.packet.net:443 "DELETE /ssh-keys/$KEY_ID HTTP/1.1" 204 0

$ nixops2 destroy -d packetDemo --debug
JSON output of nix-instantiate:
{"description":"packetDemo"}
```

**Comment by johnalotoski** [comment]
This is due to an upstream nixops bug whereby `_destroy_resources` method no longer waits to destroy resources with dependencies like it used to, due to commit: https://github.com/NixOS/nixops/commit/2f757f024906d3a437fc75852dd91912aabe677d.

Upstream issue at: https://github.com/NixOS/nixops/issues/1397

**Comment by tewfik-ghariani** [comment]
Reverting that doesn't cause the 'destroy' operation to hang? @johnalotoski

**Comment by johnalotoski** [comment]
Resolved upstream in https://github.com/NixOS/nixops/commit/d5baedfa79c32327e23d34813a7e75f5979f7560.
Nixops pin bumped in https://github.com/input-output-hk/nixops-packet/commit/cdeba70d6c2c878ad462e119e1accb935e974ac8 to resolve.
